version: '3'
services:
  be-app:
    image: be-app
    env_file:
      - development/dev.env
    build:
      context: ..
      dockerfile: development/Dockerfile.dev
    volumes:
      - ../:/app
    ports:
      - "8003:8003"
    depends_on:
      - be-db

  be-db-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: be-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
    ports:
      - "8081:8081"
    depends_on:
      - be-db

  be-db:
    image: mongo:6.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pwd

networks:
  be-network:
    external: true
